/** @type {ImageSchema[]} */
export const initialImages = [
  {
    id: 1,
    title: 'Montagnes sereines',
    imageUrl: 'https://picsum.photos/id/1018/600/600',
    category: 'Nature',
    likes: 12,
  },
  {
    id: 2,
    title: 'Rue de la ville',
    imageUrl: 'https://picsum.photos/id/1025/600/600',
    category: 'Voyage',
    likes: 5,
  },
  {
    id: 3,
    title: 'Architecture abstraite',
    imageUrl: 'https://picsum.photos/id/1060/600/600',
    category: 'Art',
    likes: 23,
  },
  {
    id: 4,
    title: 'Forêt brumeuse',
    imageUrl: 'https://picsum.photos/id/1015/600/600',
    category: 'Nature',
    likes: 45,
  },
  {
    id: 5,
    title: 'Taxi Jaune',
    imageUrl: 'https://picsum.photos/id/1071/600/600',
    category: 'Voyage',
    likes: 8,
  },
  {
    id: 6,
    title: 'Graffiti mural',
    imageUrl: 'https://picsum.photos/id/1073/600/600',
    category: 'Art',
    likes: 31,
  },
  {
    id: 7,
    title: 'Bord de mer',
    imageUrl: 'https://picsum.photos/id/1039/600/600',
    category: 'Nature',
    likes: 18,
  },
  {
    id: 8,
    title: 'Pont de la ville',
    imageUrl: 'https://picsum.photos/id/1078/600/600',
    category: 'Voyage',
    likes: 15,
  },
  {
    id: 9,
    title: 'Spirale colorée',
    imageUrl: 'https://picsum.photos/id/1080/600/600',
    category: 'Art',
    likes: 52,
  },
  {
    id: 10,
    title: 'Ciel étoilé',
    imageUrl: 'https://picsum.photos/id/1041/600/600',
    category: 'Nature',
    likes: 67,
  },
  {
    id: 11,
    title: 'Escalier urbain',
    imageUrl: 'https://picsum.photos/id/15/600/600',
    category: 'Voyage',
    likes: 9,
  },
  {
    id: 12,
    title: 'Peinture',
    imageUrl: 'https://picsum.photos/id/225/600/600',
    category: 'Art',
    likes: 28,
  },
];
